version: "3"
services:
  database:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=betinvest
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017-27019:27017-27019"